from . import translate_enzh_wmt1000k
from . import  translate_uyzh_wmt35k
from . import translate_enzh_wmt15m
from . import translate_enzh_wmtshare5w
from . import translate_enzh_wmtshare3w
from . import translate_uyzh_wmtshare5w
from . import translate_enzh_wmttransfer
from . import translate_enzh_wmttransfer3w
from . import translate_tren_wmt20w
from . import translate_tren_wmt20w1
from . import translate_uyzh_wmt35w
from . import translate_uyzh_wmt35w1
